// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJBfoJdhcAYlTR3xRNWoyj_gx02okemuc',
    appId: '1:1007388518242:web:a1a559fe376f79f8bcae3b',
    messagingSenderId: '1007388518242',
    projectId: 'pint-77ca6',
    authDomain: 'pint-77ca6.firebaseapp.com',
    storageBucket: 'pint-77ca6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZB8AbyKO8nM8fDtuQVS9XcnNwcbxYUCU',
    appId: '1:1007388518242:android:90f052e42ce98dc4bcae3b',
    messagingSenderId: '1007388518242',
    projectId: 'pint-77ca6',
    storageBucket: 'pint-77ca6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkJPmToWuAFHN_JOU8u9fHiOjEnUSoYVk',
    appId: '1:1007388518242:ios:550783cff9ab5c71bcae3b',
    messagingSenderId: '1007388518242',
    projectId: 'pint-77ca6',
    storageBucket: 'pint-77ca6.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkJPmToWuAFHN_JOU8u9fHiOjEnUSoYVk',
    appId: '1:1007388518242:ios:550783cff9ab5c71bcae3b',
    messagingSenderId: '1007388518242',
    projectId: 'pint-77ca6',
    storageBucket: 'pint-77ca6.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJBfoJdhcAYlTR3xRNWoyj_gx02okemuc',
    appId: '1:1007388518242:web:db506dc0771a9642bcae3b',
    messagingSenderId: '1007388518242',
    projectId: 'pint-77ca6',
    authDomain: 'pint-77ca6.firebaseapp.com',
    storageBucket: 'pint-77ca6.appspot.com',
  );
}
